# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

    changes:
      default:
        if_ci_failed: error

comment:
  layout: 'header, diff, files, footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '__tests__/**'
  - '**/__mocks__/**'
  - '**/test-utils/**'
  - 'e2e/**'
  - 'k6/**'
  - 'scripts/**'
  - '*.config.js'
  - '*.config.ts'
  - '*.setup.js'
  - '*.setup.ts'
  - 'app/**/layout.tsx'
  - 'app/**/loading.tsx'
  - 'app/**/error.tsx'
  - 'app/**/not-found.tsx'
  - 'types/**'

# GitHub Status Checks
github_checks:
  annotations: true

# Flags for different test types
flags:
  unittests:
    paths:
      - __tests__/
    carryforward: true

  integration:
    paths:
      - __tests__/integration/
    carryforward: true

  security:
    paths:
      - __tests__/security/
    carryforward: true
