name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

# Ensure only one deployment runs at a time
concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          echo "Deployment would occur here"
          echo "Configure Vercel CLI and deploy command"
          # vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Post-deployment health check
        run: |
          echo "Deployment completed successfully"
          # Add health check endpoint verification here

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
          fi
