name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy migrations to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: wrximmuaibfjmjrfriej
        run: |
          echo "🚀 Deploying migrations to Supabase..."
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push --include-all
          echo "✅ Migrations deployed successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Migration deployment failed!"
          echo "Please check the logs and manually apply migrations if needed."
